config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do


  devise_for :company_users
  devise_for :users, controllers: { omniauth_callbacks: "customer/omniauth_callbacks",sessions: 'customer/sessions',
                                    passwords: 'customer/passwords' }
  root to: 'customer/homes#main'
  get '/app',to: 'customer/homes#app'

  namespace :customer do

    resources :homes do
      collection do
        get :main
        post :inside
        get :android
      end
    end

    resources :menus do
      collection do
        get :home
        get :lunch
        get :dinner
      end
    end

    resources :line_items,only: [:create,:destroy] do
      member do
        put :decrease_count
      end
    end

    resources :orders,only:[:new,:create] do
        member do
          get :success
        end
    end

    resource :number_verifications,only:[] do
      post :start
      post :finish
    end

    resource :account,only:[:show]

    resources :addresses

    resource :wallet,only:[:show] do
      get :recharge
      get :add_money
      get :successful_recharge
      get :failed_recharge
    end

    namespace :app do
      resource :wallet do
        get :recharge
        get :successful_recharge
        get :failed_recharge
      end
    end

  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resource :wallet do
        get :recharge
      end
    end
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :products do
        collection do
          get :lunch
        end
      end
      resources :line_items
      resources :orders do
        collection do
          post :preview
        end
      end
      resources :sessions
      resource :wallet,only:[:show] do
        get :recharge
        post :recharge
      end
      resource :accounts,only:[:show] do
        put :update
      end
      resource :menu do
        get :lunch
        get :dinner
      end
      resource :number_verifications,only:[] do
        post :start
        get :resend
        post :finish
      end
      resources :addresses,only:[:index,:create,:update,:destroy]
      resources :feedbacks,only:[:create]
      resources :referrals,only: [:create]
      resource :promotions,only:[] do
        get :referral
      end
    end
    # Moved it out of the first namespace because of instamojo redirect..has no headers



  end

  # Have to manually specify mapping because traccars sends a port number
  get "/company/delivery_executives/update_location:80" => "company/delivery_executives#update_location"

  namespace :company do
    root 'homes#home'
    resources :homes
    resources :products
    resources :menus do
      member do
        get :add_items
        post :notify_users_lunch
        post :notify_users_dinner
      end
    end
    resources :addresses
    resources :menu_products,only: [:create,:update,:destroy] do
      member do
        post :mark_sold_out
        post :unmark_sold_out
      end
    end
    resources :orders,only:[:index,:show] do
      member do
        put :acknowledge
        put :assign
        put :inform_delivery_guy
        put :withdraw_delivery_request
        put :cancel
        put :deliver
        get :bill
        put :ask_feedback
        get :map_view
        post :send_sms
      end
      collection do
        post :sms_update
        get :by_date
        get :collections_summary
        get :last_3_months
      end
    end
    resources :current_orders do
      collection do
        get :pending
        get :acknowledged
        get :dispatched
        get :delivered
        get :cancelled
        get :chef_summary
        post :multi_assign
        get :heatmap
      end
    end
    resources :company_users do
      member do
        put :enable_otp
        put :disable_otp
        get :show_otp
        get :edit_roles
        put :update_roles
      end
    end
    resources :delivery_executives do
      member do
        put :mark_available
        get :show_location
        get :test_device
      end
      get :live_view,on: :collection
      get :dashboard,on: :collection
    end
    resources :general_promotions do
      member do
        put :enable
        put :disable
        post :apply
      end
    end
    resources :growth_partners

    resources :wallet_promotions do

    end
    resources :referrals
    resources :card_transactions,only: [:show,:index] do
    end
    resources :users do
      member do
        get :wallet
        get :feedbacks
        post :give_money
      end
    end
    resources :feedbacks
    namespace :field do
      resources :orders do
        member do
          put :accept
          put :reject
          put :mark_delivered
        end
      end
    end
  end
  resources :sitemaps, :only => :show
  get "sitemap" => "sitemaps#show"
  resources :gifts,only: [:show] do
  end

end

app/controllers/company/homes_controller.rb
class Company::HomesController < Company::BaseController

  def home
  end


end

app/controllers/customer/accounts_controller.rb
class Customer::AccountsController < Customer::BaseController

  before_filter :authenticate_user!

  def show
  end


end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < Customer::BaseController


  before_filter :set_address,except: [:index,:create]

  def create
    @address = current_user.addresses.build(address_params)
    if @address.save
      render 'create'
    else
      render json: @address.errors,status: 422
    end
  end

  def index
    render json: {default: [current_user.addresses.default_home, current_user.addresses.default_office].compact!,
                  home: current_user.addresses.normal_home, office: current_user.addresses.normal_office}
  end

  def update
    if @address.update_attributes address_params
      render json: @address
    else
      render json: @address.errors,status: 422
    end
  end

  def destroy
    @address.destroy
    render nothing: true,status: :ok,content_type: 'application/json'
  end


  private

  def address_params
     params.permit(:company,:floor,:building,:address,:flat,:address_details,:landmark,:address_type,:is_default)
  end

  def set_address
    @address = current_user.addresses.find params[:id]
  end

end

app/controllers/customer/app/base_controller.rb
class Customer::App::BaseController < ApplicationController

end

app/controllers/customer/app/wallets_controller.rb
class Customer::App::WalletsController < Customer::App::BaseController

  require 'typhoeus'

  def recharge
    #This url can be refreshed to...so customer may add same money multiple times...store payment_id in wallet
    # record and then check if already present
    payment_id = params[:payment_id]
    url = "https://www.instamojo.com/api/1.1/payments/"+payment_id+"/"
    response = ::Typhoeus.get(url,headers: {'X-Auth-Token'=>ENV['INSTAMOJO_AUTH_TOKEN'],'X-Api-Key'=>ENV['INSTAMOJO_API_KEY']})

    if response.code==200
      response = JSON.parse(response.response_body)
      if response['success']==true
        amount = response['payment']['amount']
        user_id = response['payment']['custom_fields']['Field_96618']['value']
        @user = User.find user_id
        if @user.add_to_wallet amount,payment_id,'instamojo'
         return redirect_to successful_recharge_customer_app_wallet_path
        else
          return redirect_to failed_recharge_customer_app_wallet_path
        end
      end
    end
    redirect_to failed_recharge_customer_app_wallet_path
  end



  def successful_recharge

  end

  def failed_recharge

  end

end

app/controllers/customer/base_controller.rb
class Customer::BaseController < ApplicationController


  before_filter :detect_android_and_redirect

  protected

  def detect_android_and_redirect
    redirect_to android_customer_homes_path if android?
  end

  def android?
    request.user_agent =~ /Android/i
  end


end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < Customer::BaseController

  include LocationCheck
  skip_before_filter :detect_android_and_redirect,only: [:android,:app]

  before_action :proceed_to_main_if_old_user, except: [:android,:app]

  def main
    @out_of_service = params[:out_of_service]
  end

  def android
    render layout: 'gifts'
  end

  def inside
    locality,latitude,longitude,distance = params[:locality],params[:latitude],params[:longitude],params[:distance]

    cookies[:customer] = {value: {location: {locality: locality,latitude: latitude,longitude: longitude,
                                  distance: distance}}.to_json,
                          expires: 1.month.from_now}
    # For parsing it back from cookie
    # values = JSON.parse(cookies[:customer]).with_indifferent_access

    redirect_to [:home,:customer,:menus]
  end

  def app
    redirect_to "https://play.google.com/store/apps/details?id=com.freshspoon.spoonly"
  end

end

app/controllers/customer/line_items_controller.rb
class Customer::LineItemsController < Customer::BaseController
  include CurrentCart
  before_action :set_cart

  # POST /line_items
  # POST /line_items.json
  def create
    @menu_product = MenuProduct.find(params[:menu_product_id])
    @line_item = @cart.add_menu_product(@menu_product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to request.referrer }
        format.js   { render 'update.js' }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  def decrease_count
    @line_item = @cart.line_items.find params[:id]
    respond_to do |format|
      if @line_item.decrement_count
        format.html { redirect_to request.referrer }
        format.js   { render 'update.js' }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  private


  def line_item_params
    params.require(:line_item).permit(:menu_product_id)
  end
  #...
end

app/controllers/customer/menus_controller.rb
class Customer::MenusController < ApplicationController

  include CurrentCart
  include LocationCheck

  before_filter :check_location
  before_filter :set_cart
  before_filter :set_locality, only: [:home, :lunch, :dinner]


  def home
  end

  #curl -v -H "Accept: application/vnd.healthy_lunch" -H "Content-type: application/application/x-www-form-urlencoded" -H
  # "Authorization:authentication_token"  http://localhost:3000/api/products/lunch
  def lunch
    @menu = Menu.current_lunch
    if @menu
      @cart.set_menu_and_category @menu,'lunch'
    else
      @unavailable = true
    end
  end

  def dinner
    @menu = Menu.current_dinner
    if @menu
      @cart.set_menu_and_category @menu,'dinner'
    else
      @unavailable = true
    end
  end

  private
    def set_locality
      location_hash = JSON.parse cookies[:customer]
      full_locality  = location_hash["location"]["locality"]
      # eg: ["DLF Cyber City", " Gachibowli", " Hyderabad", " Telangana", " India"]
      # DLF Cyber City  Gachibowli
      @locality = full_locality.split(',')[0,2].join(',')
    end
end

app/controllers/customer/number_verifications_controller.rb
class Customer::NumberVerificationsController < Customer::BaseController

  before_action :authenticate_user!


  # POST /api/number_verifications params {phone_number: 98989898898}
  def start
    response = NumberVerification.start current_user,params[:phone_number]
    if response
      respond_to do |format|
        format.js { render :file => "customer/number_verifications/start_verification_request.js.erb" }
      end
    else
      head 422,content_type: 'application/json'
    end
  end

  def finish
    if NumberVerification.finish current_user,params[:verification_code]
      current_user.mark_number_verified
      respond_to do |format|
        format.js {render 'customer/number_verifications/success.js.erb'}
      end
    else
      respond_to do |format|
        format.js {render 'customer/number_verifications/failure.js.erb'}
      end
    end
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  skip_before_filter :authenticate_user!

  def all
    p env["omniauth.auth"]
    user = User.from_omniauth(env["omniauth.auth"], current_user)
    if user.persisted?
      user.confirm!
      session[:login_type]=user.login_type
      sign_in_and_redirect(user)
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end

  def failure
    #handle you logic here..
    #and delegate to super.
    super
  end


  alias_method :facebook, :all
  alias_method :twitter, :all
  alias_method :linkedin, :all
  alias_method :github, :all
  alias_method :passthru, :all
  alias_method :google, :all
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  include CurrentCart

  before_action :authenticate_user!,except: [:new]

  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy,:success]
  helper_method :resource_name, :resource_class, :resource, :devise_mapping


  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to root_path, notice: "Your cart is empty"
      return
    end
    @order = Order.new
    sum_of_items = 0
    @cart.line_items.each { |item| sum_of_items += (item.quantity * item.price) }


    #TODO Refactor delivery_fee logic to a method
    if @cart.category=='lunch'
      @menu  = Menu.current_lunch

      if @menu.menu_date == Date.today
        if Time.now < Menu.today.lunch_start_time
          delivery_fee = 5
        else
          delivery_fee = 15
        end
      else
        # It is after 3:30 and he is seeing next day menu..so only 5 rs delivery
        delivery_fee = 5
      end
    else
      delivery_fee = 10
    end

    @delivery_fee = delivery_fee

    @cart_total = sum_of_items + @delivery_fee
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.build(order_params)
    menu_date = @cart.menu.menu_date
    @order.delivery_time = "#{menu_date.year}-#{menu_date.month}-#{menu_date.day}-"+order_params[:delivery_time]
    @order.add_line_items_from_cart(@cart)
    @order.category = @cart.category
    if order_params[:delivery_time].present?
      if @order.save

        #TODO Refactor delivery_fee logic to a method
        if @cart.category=='lunch'
          @menu  = Menu.current_lunch

          if @menu.menu_date == Date.today
            if Time.now < Menu.today.lunch_start_time
              delivery_fee = 5
            else
              delivery_fee = 15
            end
          else
            # It is after 3:30 and he is seeing next day menu..so only 5 rs delivery
            delivery_fee = 5
          end
        else
          delivery_fee = 10
        end
        @order.update_attributes(delivery_fee: delivery_fee)
        #TODO Why not @cart.destroy
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        @order.start_process!
        # OrderNotifier.received(@order).deliver
        respond_to do |format|
          format.html {        redirect_to success_customer_order_path @order,notice: 'Your order has been created !'     }
          format.js {render 'customer/orders/create_success'}
        end

      else
        respond_to do |format|
          format.html { render action: 'new'}
          format.js {render 'customer/orders/create_failure'}
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'new'}
        format.js {render 'customer/orders/create_failure'}
      end
    end
  end

  def success

  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    resource.class
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:address_id, :pay_type,:category,:delivery_time)
  end


end

app/controllers/customer/passwords_controller.rb
class Customer::PasswordsController < Customer::BaseController

  def new
    redirect_to root_path
  end

  def create
    redirect_to root_path
  end

end

app/controllers/customer/sessions_controller.rb
class Customer::SessionsController < Customer::BaseController

  def new
    redirect_to root_path
  end

  def create
    redirect_to root_path
  end

  def destroy
    sign_out current_user
    cookies.delete(:customer)
    session[:login_type] = nil
    redirect_to root_path
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/customer/homes/_how_it_works.html.haml
.section-two#about
  %h2.title What's for lunch?
  %h3.title
    Finally has an easy answer
  .sep


  .about-section
    .col1.pic
      = image_tag "hot_food1.jpg"
    .col2.text.text-1
      %p.about-section-text-title Daily Menus
      %p.about-section-text-desc
        Treat yourself with a different meal everyday, thanks to our daily changing menus.

      %p.about-section-text-title.spacer Chef Made Meals:
      %p.about-section-text-desc
        Our Chefs believe in creating the right fusion of Indian and International cuisines from across the globe.

      %p.about-section-text-title.spacer Fresh Ingredient, Tasty Meals
      %p.about-section-text-desc
        Who said healthy food can't also be delicious? Our chefs use fresh and seasonal ingredients to make affordable, tasty and nourishing meals.
    .about-section-title
      Fresh & Wholesome

  .about-section
    .col1.text.text-2
      %p.about-section-text-title Web and Mobile app
      %p.about-section-text-desc
        Whether you're on your laptop or smart phone, we've got you covered. Order via web or mobile as per your
        convenience.
    .col2.pic
      = image_tag "laptop_logo.jpg",style: 'height: 240px;width: 380px; margin-top: 60px;margin-left: 40px'
    .about-section-title.tap-to-order
      %p Tap to
      %p Order

  .about-section
    .col1.pic
      = image_tag "rider1.jpg"
    .col2.text.text-3
      %p.about-section-text-title Delivered at your convenience
      %p.about-section-text-desc
        Hungry and want your food right away? Our riders deliver
        your meals in a jiffy.
    .about-section-title
      On time delivery

  .about-section.location-form-container
    %h2.title Start eating better now!
    -#%h3.desc Start eating better now!
    -#Add the below input later
    -#- if controller_name=='homes'
    -#  .location-form
    -#    = render "customer/homes/location_form"

  .about-section-testimonals
    .testimonals-heart
      %i.fa.fa-heart
    %h2 What our customers have to say?

    .testimonals-holder
      .testimony
        %span.name Ravi,
        %span.city Hyderabad
        .comment
          %i.fa.fa-quote-left
          %span I really like the idea of a daily changing menu. Love the food and packaging.
          %i.fa.fa-quote-right

      .testimony
        %span.name Harsha,
        %span.city Hyderabad
        .comment
          %i.fa.fa-quote-left
          %span  Good lunch menu options at a decent price!
          %i.fa.fa-quote-right

      .testimony
        %span.name Goutham,
        %span.city Hyderabad
        .comment
          %i.fa.fa-quote-left
          %span The food is very good. I love that I can order in advance and specify a delivery time.
          %i.fa.fa-quote-right

app/views/customer/homes/_location_form.html.haml
= form_tag inside_customer_homes_path, id: 'locationForm', class: "form-horizontal" do
  .form-group
    .city-location
      %span Hyderabad
      = text_field_tag 'locality','',id: 'searchTextField', size: '40',placeholder: 'Enter Location eg. Hitec City '
      = hidden_field_tag 'latitude'
      = hidden_field_tag 'longitude'
      = hidden_field_tag 'distance'
    = submit_tag 'See Menu', class: "btn btn-default"

app/views/customer/homes/android.html.haml
.download-app
  #android.text-center
    .top
      .logo
        = image_tag 'spoonly_referral_logo.gif'
      .features
        %p Chef Made Meals
        %p Fresh & Wholesome
        %p Daily Changing Menu
    .sep
    .app
      %h2 Install The App
      %p Takes only 1 minute

      %a{:href => "https://play.google.com/store/apps/details?id=com.freshspoon.spoonly"}
        %img{:alt => "Get it on Google Play", :src => "https://developer.android.com/images/brand/en_generic_rgb_wo_45.png"}/

app/views/customer/homes/main.html.haml
= title 'Order Fresh, Tasty Food Online in Hyderabad. Order Lunch and Dinner from our ever changing daily menu'
= content_for :description, 'Freshly prepared tasty,wholesome meals. Delivered to your Desk. Order lunch and dinner online'
= content_for :keywords, 'Home Delivery, Lunch ,Office Lunch, Dinner, Healthy Food,Wholesome Meals, Order Food Online,
 Online Food delivery'
- meta og: { description: "Chef made meals.Delivered to your desk. Order lunch & dinner from our daily changing menu" ,url: "http://www.spoonly.in",title: "Freshly prepared tasty,
 wholesome meals delivered to your desk | Spoonly"}

#customer_home
  .section-one
    .col-xs-12
      .text-container.text-center
        %h2{'style'=> "font-size: 31px;"} Reclaim
        %h1{'style'=> "font-size: 44px; "} Mealtime
        %br
        -#  TODO Make below font size as 12 px
        %p{'style'=> "font-size: 15px;"}  Fresh. Wholesome. Chef-made
        %p{'style'=> "font-size: 15px;"}  Delivered to your desk.
        %br
        .row
          .col-xs-1
          = render 'location_form'
  = render 'how_it_works'


%script{src: "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places" }

:javascript
  function initialize() {

  var input = document.getElementById('searchTextField');
  var southWest = new google.maps.LatLng( 17.323550, 78.285136 );
  var northEast = new google.maps.LatLng( 17.627775, 78.630175 );
  var hyderabadBounds = new google.maps.LatLngBounds( southWest, northEast );

  var options = {
      //bounds: hyderabadBounds,
      componentRestrictions: { country: 'in' }
  };

  var autocomplete = new google.maps.places.Autocomplete(input,options);
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
     var place = autocomplete.getPlace();
     var dest_lat = place.geometry.location.lat()
     var dest_long = place.geometry.location.lng()
     dest = new google.maps.LatLng(dest_lat,dest_long);
     //Analytics code for place
     analytics.track('Entered location', {
       place: place.formatted_address
     });

     $('#locationForm').find('#latitude').val(dest_lat);
     $('#locationForm').find('#longitude').val(dest_long);
     $('#locationForm').submit();

  });
  }

  google.maps.event.addDomListener(window, 'load', initialize);
  $(document).on('page:load',initialize)

- if @out_of_service
  :javascript
    setTimeout(function(){
      alert("We're sorry :(  Currently we do not serve in your area. We currently serve in Hitec City, Gachibowli and parts of Kondapur.");
     }, 50);