config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do


  devise_for :company_users
  devise_for :users, controllers: { omniauth_callbacks: "customer/omniauth_callbacks",sessions: 'customer/sessions',
                                    passwords: 'customer/passwords' }
  root to: 'customer/homes#main'
  get '/app',to: 'customer/homes#app'

  namespace :customer do

    resources :homes do
      collection do
        get :main
        post :inside
        get :android
      end
    end

    resources :menus do
      collection do
        get :home
        get :lunch
        get :dinner
      end
    end

    resources :line_items,only: [:create,:destroy] do
      member do
        put :decrease_count
      end
    end

    resources :orders,only:[:new,:create] do
        member do
          get :success
        end
    end

    resource :number_verifications,only:[] do
      post :start
      post :finish
    end

    resource :account,only:[:show]

    resources :addresses

    resource :wallet,only:[:show] do
      get :recharge
      get :add_money
      get :successful_recharge
      get :failed_recharge
    end

    namespace :app do
      resource :wallet do
        get :recharge
        get :successful_recharge
        get :failed_recharge
      end
    end

  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resource :wallet do
        get :recharge
      end
    end
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :products do
        collection do
          get :lunch
        end
      end
      resources :line_items
      resources :orders do
        collection do
          post :preview
        end
      end
      resources :sessions
      resource :wallet,only:[:show] do
        get :recharge
        post :recharge
      end
      resource :accounts,only:[:show] do
        put :update
      end
      resource :menu do
        get :lunch
        get :dinner
      end
      resource :number_verifications,only:[] do
        post :start
        get :resend
        post :finish
      end
      resources :addresses,only:[:index,:create,:update,:destroy]
      resources :feedbacks,only:[:create]
      resources :referrals,only: [:create]
      resource :promotions,only:[] do
        get :referral
      end
    end
    # Moved it out of the first namespace because of instamojo redirect..has no headers



  end

  # Have to manually specify mapping because traccars sends a port number
  get "/company/delivery_executives/update_location:80" => "company/delivery_executives#update_location"

  namespace :company do
    root 'homes#home'
    resources :homes
    resources :products
    resources :menus do
      member do
        get :add_items
        post :notify_users_lunch
        post :notify_users_dinner
      end
    end
    resources :addresses
    resources :menu_products,only: [:create,:update,:destroy] do
      member do
        post :mark_sold_out
        post :unmark_sold_out
      end
    end
    resources :orders,only:[:index,:show] do
      member do
        put :acknowledge
        put :assign
        put :inform_delivery_guy
        put :withdraw_delivery_request
        put :cancel
        put :deliver
        get :bill
        put :ask_feedback
        get :map_view
        post :send_sms
      end
      collection do
        post :sms_update
        get :by_date
        get :collections_summary
        get :last_3_months
      end
    end
    resources :current_orders do
      collection do
        get :pending
        get :acknowledged
        get :dispatched
        get :delivered
        get :cancelled
        get :chef_summary
        post :multi_assign
        get :heatmap
      end
    end
    resources :company_users do
      member do
        put :enable_otp
        put :disable_otp
        get :show_otp
        get :edit_roles
        put :update_roles
      end
    end
    resources :delivery_executives do
      member do
        put :mark_available
        get :show_location
        get :test_device
      end
      get :live_view,on: :collection
      get :dashboard,on: :collection
    end
    resources :general_promotions do
      member do
        put :enable
        put :disable
        post :apply
      end
    end
    resources :growth_partners

    resources :wallet_promotions do

    end
    resources :referrals
    resources :card_transactions,only: [:show,:index] do
    end
    resources :users do
      member do
        get :wallet
        get :feedbacks
        post :give_money
      end
    end
    resources :feedbacks
    namespace :field do
      resources :orders do
        member do
          put :accept
          put :reject
          put :mark_delivered
        end
      end
    end
  end
  resources :sitemaps, :only => :show
  get "sitemap" => "sitemaps#show"
  resources :gifts,only: [:show] do
  end

end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::BaseController

  before_action :authenticate_user!
  before_action :set_order, only: [:show, :cancel]

  respond_to :json

  # POST /api/orders
  # POST /api/orders.json
  def create
    @order = current_user.orders.create! order_params
    params[:line_item].each do |li|
      menu_product = MenuProduct.find custom_line_item_params(li)['menu_product_id']
      # Slowly change it to menu_product.price...as that is the price that gets recorded
      new_params = custom_line_item_params(li).merge({price: menu_product.product.price})
      @order.line_items.create!(new_params)
    end


    # Refactor delivery_fee logic to a method
    if order_params[:category]=='lunch'
      @menu  = Menu.current_lunch

      if @menu.menu_date == Date.today
        if Time.now < Menu.today.lunch_start_time
          delivery_fee = 5
        else
          delivery_fee = 15
        end
      else
        # It is after 3:30 and he is seeing next day menu..so only 5 rs delivery
        delivery_fee = 5
      end
    else
      delivery_fee = 10
    end
    @order.update_attributes(delivery_fee: delivery_fee)

    @order.start_process!
    render json: @order
  rescue Exception=>e
    HealthyLunchUtils.log_error e.message,e
    @order.destroy if @order
    render status: :error
  end

  def index
    @orders = current_user.orders.includes(:debit).includes(:line_items).order(delivery_time: :desc)
    render json: {orders: @orders}
  end

  def show
    render json: @order.to_json(details: true)
  end

  def cancel

  end

  def preview
    item_total = 0
    item_quantity = 0
    if params[:line_item].present?
      params[:line_item].each do |li|
        menu_product = MenuProduct.find custom_line_item_params(li)['menu_product_id']
        quantity = custom_line_item_params(li)['quantity'].to_f
        item_quantity = item_quantity + quantity
        # When u add item to menu...and later change product price...it doesnt get reflected in menu_product price..and it shouldnt..so have a menu to edit the menu product price after a menu priduct has been created
        item_total = item_total + menu_product.product.price*quantity
      end

      # Refactor delivery_fee logic to a method
      if order_params[:category]=='lunch'
        @menu  = Menu.current_lunch

        if @menu.menu_date == Date.today
          if Time.now < Menu.today.lunch_start_time
            delivery_fee = 5
          else
            delivery_fee = 15
          end
        else
          # It is after 3:30 and he is seeing next day menu..so only 5 rs delivery
          delivery_fee = 5
        end
      else
        delivery_fee = 10
      end


      bill_total = item_total + delivery_fee
      grand_total = bill_total

      prepaid_amount = ((grand_total >= current_user.wallet.balance) ? current_user.wallet.balance : grand_total )
      cash_to_pay = (prepaid_amount > 0) ?  (grand_total - prepaid_amount) : grand_total

      response = {delivery_fee: delivery_fee,grand_total: grand_total,item_total: item_total,item_quantity: item_quantity,prepaid_amount: prepaid_amount,cash_to_pay: cash_to_pay}
      render json: response
    end
      # {delivery_fee: delivery_fee, promotion: {coupon_code: BACK50,discount: 50},wallet_cash_used: 40 }
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:address_id, :pay_type,:delivery_time,:category)
  end

  def custom_line_item_params(par = {})
    par.permit(:menu_product_id,:quantity)
  end

  def line_item_params #this is the default one, without parameters
    custom_line_item_params(params.require(:line_item))
  end

  def set_order
    @order = current_user.orders.find params[:id]
  end

end

app/controllers/company/field/base_controller.rb
class Company::Field::BaseController < Company::BaseController

  layout 'field/application'

  before_filter :authenticate_delivery_executive

  def authenticate_delivery_executive
    @delivery_executive = DeliveryExecutive.where(email: current_company_user.email).first
    redirect_to root_path unless current_company_user.has_role? :delivery_executive
  end

end

app/controllers/company/field/orders_controller.rb
class Company::Field::OrdersController < Company::Field::BaseController

  def index
    @undelivered_orders = @delivery_executive.orders.where(state: ['informed_delivery_guy','dispatched']).today.order(delivery_time: :asc)
    @delivered_orders = @delivery_executive.orders.where(state: ['delivered']).today.order(delivery_time: :desc)
    if Time.now.hour > 16
      @undelivered_orders = @undelivered_orders.where(category: 'dinner').order(delivery_time: :asc)
      @delivered_orders = @delivered_orders.where(category: 'dinner').order(delivery_time: :asc)
    end
  end

  def accept
    @order = Order.find params[:id]
    if @order.mark_dispatched!
      redirect_to request.referrer,notice: 'Successfully Accepted Order!'
    end
  end

  def reject
    @order = Order.find params[:id]
    if @order.reject_delivery_request!
      redirect_to request.referrer,alert: "Rejected Delivery Request"
    else
      redirect_to request.referrer,alert: 'Some error occured. Please check again!'
    end
  end

  def mark_delivered
    @order = Order.find params[:id]
    if @order.deliver!
      redirect_to request.referrer,notice: 'Successfully Marked Delivered!'
    end
  end

end

app/controllers/company/orders_controller.rb
class Company::OrdersController < Company::BaseController

  before_filter :authenticate_dispatcher!, except: [:sms_update]
  before_filter :set_order, except: [:index, :sms_update, :by_date, :collections_summary,:last_3_months]
  before_filter :authenticate_sms_sender!, only: [:sms_update]
  before_filter :authenticate_admin!, only: [:last_3_months]

  def index
    @orders = Order.order(delivery_time: :desc).includes(:user).includes(:address).paginate page: params[:page]
  end

  def by_date
    if params[:date]
      @delivery_date = DateTime.new params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i
      @orders = Order.find_by_date @delivery_date
    end
  end

  def show
  end

  def bill
  end

  def acknowledge
    @order.acknowledge!
    redirect_to request.referrer
  end

  def assign
    if @order.update_attributes(order_params)
      @order.dispatch_with order_params[:delivery_executive_id]
      redirect_to [:company, @order], notice: 'Successfully assigned to delivery executive'
    else
      redirect_to [:company, @order], alert: 'Unable to assign'
    end
  end

  def inform_delivery_guy
    @order = Order.find params[:id]
    @delivery_executive = DeliveryExecutive.find params[:inform_delivery_executive_id]
    if @order.inform_delivery_guy @delivery_executive
      redirect_to [:acknowledged,:company,:current_orders],notice: "Informed #{@delivery_executive.name}"
    else
      redirect_to request.referrer,alert: 'Some error occured. Please check again!'
    end
  end

  def withdraw_delivery_request
    @order = Order.find params[:id]
    if @order.withdraw_delivery_request!
      redirect_to [:acknowledged,:company,:current_orders],notice: "Withdrawn Delivery Request"
    else
      redirect_to request.referrer,alert: 'Some error occured. Please check again!'
    end
  end

  def cancel
    if @order.cancel!
      redirect_to [:company, @order]
    end
  end

  def sms_update
    HealthyLunchUtils.log_info "Inside sms update before if loop"
    if params[:secret]==ENV['TELERIVET_SECRET']
      from_number = params['from_number'][3..13]
      if DeliveryExecutive.allowed_numbers.include? from_number
        message = params['content'].strip
        message = message.split(' ')
        order_ids = message[0].split(',')
        HealthyLunchUtils.log_info "Order ids are #{order_ids}"
        if (message[1].downcase=='done') || (message[1].downcase=='d')
          HealthyLunchUtils.log_info "going to find orders #{order_ids} and mark delivered"
          @orders = Order.where id: order_ids
          @orders.where(state: 'dispatched').each(&:deliver!)
          return render nothing: true
        elsif message[1].downcase=='ok'
          HealthyLunchUtils.log_info 'Acknowledged by delivery boy'
          @orders = Order.where id: order_ids
          @orders.where(state: 'informed_delivery_guy').each(&:mark_dispatched!)
          return render nothing: true
        else
          HealthyLunchUtils.log_info 'Wrong format'
          return render nothing: true
        end
      else
        # Got sms from unknown number
        HealthyLunchUtils.log_info "Got sms from unknown number"
        return render nothing: true
      end
    else
      HealthyLunchUtils.log_info "Secret doesnt match telerivet"
      head 403
    end
  rescue Exception => e
    HealthyLunchUtils.log_error 'SMS not in format', e
    return render nothing: true
  end

  def deliver
    if @order.deliver!
      redirect_to request.referrer, notice: 'Order has been marked delivered'
    end
  end

  def collections_summary
    if params[:date]
      @delivery_date = DateTime.new params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i
    else
      @delivery_date = Date.today
    end
    @category = params[:category] || 'lunch'
    @delivered_orders = Order.find_by_date(@delivery_date).includes(:delivery_executive).includes(:debit).includes(:line_items).includes(:user).where.not(state: ['cancelled']).where(category: @category)
  end

  def ask_feedback
    if @order.delivered?
      @order.ask_for_feedback
      redirect_to request.referrer, notice: 'Asked for feedback'
    else
      redirect_to request.referrer, alert: 'Order hasnt been delivered yet'
    end
  end


  def map_view
    @address = @order.address
    if @address.has_location?

      @delivery_executives = DeliveryExecutive.all.select do |d|
        if (d.last_seen_delivery_executive_location)
          if(d.last_seen_delivery_executive_location.last_seen > Time.now - 2.hours)
            distance = d.last_seen_delivery_executive_location.location.distance_from @address.latitude,@address.longitude
          end
        end

      end

      @delivery_hash = @delivery_executives.collect do |de|
        if  de.last_seen_delivery_executive_location
          if @order.delivery_executive == de
             selected_exec = true
          else
            selected_exec = false
          end
          [de.last_seen_delivery_executive_location.location.try(:latitude).try(:to_f),de.last_seen_delivery_executive_location.location.try(:longitude).try(:to_f),de.name,
           de.last_seen_delivery_executive_location.last_seen.strftime("%l:%M %p, %a  %-d %b"),selected_exec,de.id,de.last_seen_delivery_executive_location.location.speed.to_i]
        end
      end.select(&:present?)
      @order_hash = [[@address.latitude.try(:to_f),@address.longitude.try(:to_f),@order.delivery_time_range,@order.user.name,@address.formatted]]
      end
  end

  def send_sms
    if DeliveryExecutiveMessenger.dispatch_by_sms(@order,@order.sms_form)
      redirect_to request.referrer,notice: 'SMS has been sent!'
    else
      redirect_to request.referrer,alert: 'ERROR: SMS NOT SENT!!!'
    end
  end

  def last_3_months
    @orders = Order.where("created_at > ?",85.days.ago).order(:created_at)

    spreadsheet_name = 'Spoonly 3 month orders'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet :name => spreadsheet_name

    @orders.each_with_index  { |order, i|
      sheet1.row(i).replace [order.id, order.user_id, order.formatted_delivery_time, order.detail_line_items,order.grand_total]
    }
    export_file_path = [Rails.root, "public","spoonly_#{ DateTime.now.to_s }.xls"].join("/")
    book.write export_file_path
    send_file export_file_path, :content_type => "application/vnd.ms-excel", :disposition => 'inline'

  end


  private

  def order_params
    params.require(:order).permit(:delivery_executive_id)
  end

  def set_order
    @order = Order.find params[:id]
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/company/field/orders/_assigned_order_modal.html.haml
#menu_unavailable_modal.modal{:title => "My modal", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role=> "dialog","style"=>"margin-top: 100px;"}

  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      .modal-body
        - link = company_field_orders_path
        %p.msg-big NEW ORDER RECEIVED!
        %a{"aria-hidden" => "true", "data-dismiss" => "modal"}
          %p.msg= link_to "CLICK HERE TO SEE LATEST ORDER",link,class: 'btn btn-primary'

app/views/company/field/orders/_new_order_handling.html.haml
= render 'company/field/orders/assigned_order_modal'
= render 'company/field/orders/withdrawn_request_modal'
= render 'company/field/orders/test_device_modal'

.row
  :javascript
    var initialize = function(){

    console.log('initializing');
    // Enable pusher logging - don't include this in production
    Pusher.log = function(message) {
      if (window.console && window.console.log) {
        window.console.log(message);
      }
    };

    var pusher = new Pusher("#{Pusher.key}", {
      encrypted: true
    });
    var channel = pusher.subscribe('orders');
    channel.bind("assigned_to_#{@delivery_executive.id}", function(data) {

    var sound = new Howl({
      urls: ["#{asset_path('company/field_order.mp3')}"],
      loop: true
    }).play();
    window.navigator.vibrate([500,500,500,500])

    $('#new_order_alert').show()
      //sound.stop();
     $('#menu_unavailable_modal').show();

    });


    //Bind to withdraw_requests
        channel.bind("withdraw_request_from_#{@delivery_executive.id}", function(data) {



        var sound = new Howl({
          urls: ["#{asset_path('company/field_order.mp3')}"],
          loop: true,
          volume: 1.0
        }).play();

        $('#new_order_alert').show()
          //sound.stop();
         $('#withdrawn_request_modal').find('#order_data').html(data['info'])
         $('#withdrawn_request_modal').show();
         window.navigator.vibrate([500,500,500,500])


        });


       //Bind to test field devices
       channel.bind("test_device_#{@delivery_executive.id}", function(data) {

       var sound = new Howl({
         urls: ["#{asset_path('company/field_order.mp3')}"],
         loop: true
       }).play();
       window.navigator.vibrate([500,500,500,500])

        $('#test_device_modal').show();

       });

    }
    initialize();

app/views/company/field/orders/_test_device_modal.html.haml
#test_device_modal.modal{:title => "My modal", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role=> "dialog","style"=>"margin-top: 100px;"}

  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      .modal-body
        - link = company_field_orders_path
        %p.msg-big Testing device..Is your alarm ringing ?
        %a{"aria-hidden" => "true", "data-dismiss" => "modal"}
          %p.msg= link_to "Tap here to stop alarm",link,class: 'btn btn-primary'

app/views/company/field/orders/_withdrawn_request_modal.html.haml
#withdrawn_request_modal.modal{:title => "My modal", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role=> "dialog","style"=>"margin-top: 100px;"}

  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      .modal-body
        - link = company_field_orders_path
        %p.msg-big ORDER WITHDRAWN !
        %p#order_data
        %a{"aria-hidden" => "true", "data-dismiss" => "modal"}
          %p.msg= link_to "CLICK OK TO REFRESH",link,class: 'btn btn-primary'

app/views/company/field/orders/index.html.haml
- content_for :head do
  :javascript
    history.pushState(null, null, 'orders');
    window.addEventListener('popstate', function(event) {
    history.pushState(null, null, 'orders');
    });
= title 'Todays Orders'

.container-fluid
  .alert.alert-danger#new_order_alert{'style'=> "display: none"}
    New order has been received! Refresh Page

  - if @undelivered_orders.present?


    .row
      - line_items = LineItem.where(order: @undelivered_orders)
      .col-xs-6
        %h3
          ="VEG-#{line_items.select(&:vegetarian).sum(&:quantity)}"
      .col-xs-6
        %h3
          = "NONVEG-#{line_items.reject(&:vegetarian).sum(&:quantity)}"

    - @undelivered_orders.each do |order|
      .row
        - user = order.user
        .col-xs-8
          %br
          = "##{order.id}, #{user.name[0..10]}"
          = link_to 'CALL',"tel:#{user.profile.phone_number}",class: 'btn-primary btn btn-sm'
          %br
          = "#{order.address.formatted}."
          - if order.address.has_location?
            = link_to "Map","geo:?q=#{order.address.latitude},#{order.address.longitude}"
          %br
          %b= "#{order.formatted_delivery_time.split(' ')[0]+" "+order.formatted_delivery_time.split(' ')[1]}"
          %br
          = "#{order.detail_line_items}"
          &#8377
          ="#{order.cash_to_pay.to_i}"
        .col-xs-4
          %br
            %br
          - if order.informed_delivery_guy?
            = link_to 'Accept',accept_company_field_order_path(order),method: :put,class: 'btn btn-danger'
            %br
              %br
            &emsp;
            = link_to 'Reject',reject_company_field_order_path(order),method: :put,data: {confirm: 'Do you want to REJECT this order ?'}
          - else
            - if order.dispatched?
              = link_to 'Mark Delivered!',mark_delivered_company_field_order_path(order),method: :put,class: 'btn btn-primary',data:{confirm: "Mark order #{order.id},#{order.user.name} as delivered ?"}
            - else
              = order.state.upcase
  - else
    .col-xs-3
    .col-xs-8
      No Orders To Be Delivered!


  %br
    %br
  %br
    %br
  %br
    %br
  %br
    %br
  %br
    %br
  %hr
  %hr

  - if @delivered_orders.present?
    .row
      %h4 DELIVERED ORDERS
    - @delivered_orders.each do |order|
      .row
        - user = order.user
        .col-xs-8
          %br
          = "##{order.id}, #{user.name[0..10]}"
          = link_to 'CALL',"tel:0#{user.profile.phone_number}",class: 'btn-primary btn btn-sm'
          %br
          = "#{order.address.formatted}."
          %br
          %b= "#{order.formatted_delivery_time.split(' ')[0]+" "+order.formatted_delivery_time.split(' ')[1]}"
          %br
          = "#{order.brief_line_items}"
          &#8377
          = "#{order.cash_to_pay.to_i}"
        .col-xs-4
          %br
            %br
          Delivered



    %br
  = render 'company/field/orders/new_order_handling'